package com.fse.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Product")
public class Product {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String productId;

	@DynamoDBAttribute
	private String productName;

	@DynamoDBAttribute
	private String shortDesc;

	@DynamoDBAttribute
	private String detailedDesc;

	@DynamoDBAttribute
	private String category;

	@DynamoDBAttribute
	private BigDecimal price;

	@DynamoDBAttribute
	private Date bidEndDate;
	
//	@DynamoDBAttribute
//	private User user;

}
